### ISSUE TITLE
Shared preferences required to use library

### ISSUE THREAD

**Issue by duindain** [Skyost/rate_my_app#36]
**Describe the bug**
I've just installed this library and running my app i get an exception 
```
The getter 'millisecondsSinceEpoch' was called on null.
Receiver: null
Tried calling: millisecondsSinceEpoch
```
It looks like the library is assuming certain keys exist in the shared preferences but there is no instruction to create them and they don't seem to be in the example app

**To Reproduce**
Include the library in an app
Initialise with recommended settings
```
RateMyApp rateMyApp = RateMyApp(
    preferencesPrefix: 'rateMyApp_',
    minDays: 7,
    minLaunches: 10,
    remindDays: 7,
    remindLaunches: 10,
    googlePlayIdentifier: 'app.namespace',
    appStoreIdentifier: 'appid',
  );
```

Call opendialog if needed
```
if(rateMyApp.shouldOpenDialog)
      rateMyApp.showStarRateDialog(
        context,
        title: 'Rate this app', // The dialog title.
        message: 'Do you enjoy the app? Please take a little time to leave a rating :', // The dialog message.
        onRatingChanged: (stars) { // Triggered when the user updates the star rating.
          return [ // Return a list of actions (that will be shown at the bottom of the dialog).
            FlatButton(
              child: Text('OK'),
              onPressed: () async {
                print('Thanks for the ' + (stars == null ? '0' : stars.round().toString()) + ' star(s) !');
                if(stars.round() <= 2)
                {

                }
                // You can handle the result as you want (for instance if the user puts 1 star then open your contact page, if he puts more then open the store page, etc...).
                // This allows to mimic the behavior of the default "Rate" button. See "Advanced > Broadcasting events" for more information :
                await rateMyApp.callEvent(RateMyAppEventType.rateButtonPressed);
                Navigator.pop<RateMyAppDialogButton>(context, RateMyAppDialogButton.rate);
              },
            ),
          ];
        },
        ignoreIOS: false, // Set to false if you want to show the native Apple app rating dialog on iOS.
        dialogStyle: DialogStyle( // Custom dialog styles.
          titleAlign: TextAlign.center,
          messageAlign: TextAlign.center,
          messagePadding: EdgeInsets.only(bottom: 20),
        ),
        starRatingOptions: StarRatingOptions(),
        // Custom star bar rating options.
        //I had to comment this out because it doesn't seem to exist
//onDismissed: () => rateMyApp.callEvent(RateMyAppEventType.laterButtonPressed), // Called when the user dismissed the dialog (either by taping outside or by pressing the "back" button).
      );
```

**Expected behavior**
Documentation of required shared preference keys and how to populate them
Or have the keys auto generate if the values are missing
The shared preferences library has containsKey so check before using the value and if not found default value it? (_sharedPreferences.containsKey(key) ? sharedPreferences.getString(key) : emptyValue;_)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Smartphone (please complete the following information):**
 - Device:Android emulator Pixel 3
 - OS: Android
 - Version 29

I have the following versions installed related to this library
- Flutter version 1.12.13+hotfix.5
- rate_my_app: ^0.5.0+3
- smooth_star_rating: ^1.0.4+2
- shared_preferences: ^0.5.6+1

Stacktrace
```
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      MinimumDaysCondition.isMet (package:rate_my_app/src/conditions.dart:81:68)
#2      RateMyApp.shouldOpenDialog.<anonymous closure> (package:rate_my_app/src/core.dart:80:80)
#3      ListMixin.firstWhere (dart:collection/list.dart:144:15)
#4      RateMyApp.shouldOpenDialog (package:rate_my_app/src/core.dart:80:43)
```

**Comment by Skyost** [comment]
You should call [`init()`](https://github.com/Skyost/rate_my_app/blob/master/example/lib/main.dart#L13) before using the library.

**Comment by duindain** [comment]
Sorry about that I copied the second example which was well under the init call and must have missed it

**Comment by Skyost** [comment]
No problem :wink:

**Comment by Skyost** [comment]
No problem :wink:
